### ISSUE TITLE
Create CAPTCHA integration for authentication

### ISSUE THREAD

**Issue by LR-Gutierrez** [gustavosantaella/finance#32]
This will prevent unwanted request in those endpoints

**Comment by gustavosantaella** [comment]
> This will prevent unwanted request in those endpoints

It's good idea to check the user

**Comment by gustavosantaella** [comment]
> This will prevent unwanted request in those endpoints

I thin that it can't implement captchat on mobile with flutter 
[https://stackoverflow.com/questions/73084944/recaptcha-v3-on-mobile-devices](url)
