### ISSUE TITLE
Integrate services to prevent ddos attacks, among others

### ISSUE THREAD

**Issue by LR-Gutierrez** [gustavosantaella/finance#33]
A good option could be Cloudflare

**Comment by gustavosantaella** [comment]
Do you think that to do that manually in the server is a good idea ? Or you prefer to use some provider

**Comment by gustavosantaella** [comment]
> A good option could be Cloudflare 

Do you think that to do that manually in the server is a good idea ? Or you prefer to use some provider

**Comment by LR-Gutierrez** [comment]
I'm not 100% sure if cloudflare works like this, but if it does I think that using an external service to protect DDOS attacks is a better idea, because the request gets to the external service at first, validates it and then returns to the app. This would not occur when validating manually since the requests would be made on the same IP address
